/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Merchant {
  'installedSectionIds' : Array<string>,
  'billingStatus' : string,
  'shopDomain' : string,
  'installDate' : bigint,
  'planType' : string,
}
export interface Section {
  'id' : string,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'category' : string,
  'isPro' : boolean,
}
export interface _SERVICE {
  'getAllSections' : ActorMethod<[], Array<Section>>,
  'getInstalledSections' : ActorMethod<[string], Array<Section>>,
  'getMerchant' : ActorMethod<[string], Merchant>,
  'getMerchantStats' : ActorMethod<
    [string],
    { 'totalInstalled' : bigint, 'billingStatus' : string, 'planType' : string }
  >,
  'getSection' : ActorMethod<[string], Section>,
  'installSection' : ActorMethod<[string, string], Merchant>,
  'removeSection' : ActorMethod<[string, string], Merchant>,
  'updateMerchantPlan' : ActorMethod<[string, string, string], Merchant>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];