/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Section = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : IDL.Text,
  'isPro' : IDL.Bool,
});
export const Merchant = IDL.Record({
  'installedSectionIds' : IDL.Vec(IDL.Text),
  'billingStatus' : IDL.Text,
  'shopDomain' : IDL.Text,
  'installDate' : IDL.Int,
  'planType' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
  'getInstalledSections' : IDL.Func([IDL.Text], [IDL.Vec(Section)], ['query']),
  'getMerchant' : IDL.Func([IDL.Text], [Merchant], []),
  'getMerchantStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalInstalled' : IDL.Nat,
          'billingStatus' : IDL.Text,
          'planType' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getSection' : IDL.Func([IDL.Text], [Section], ['query']),
  'installSection' : IDL.Func([IDL.Text, IDL.Text], [Merchant], []),
  'removeSection' : IDL.Func([IDL.Text, IDL.Text], [Merchant], []),
  'updateMerchantPlan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Merchant],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Section = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : IDL.Text,
    'isPro' : IDL.Bool,
  });
  const Merchant = IDL.Record({
    'installedSectionIds' : IDL.Vec(IDL.Text),
    'billingStatus' : IDL.Text,
    'shopDomain' : IDL.Text,
    'installDate' : IDL.Int,
    'planType' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
    'getInstalledSections' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Section)],
        ['query'],
      ),
    'getMerchant' : IDL.Func([IDL.Text], [Merchant], []),
    'getMerchantStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalInstalled' : IDL.Nat,
            'billingStatus' : IDL.Text,
            'planType' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getSection' : IDL.Func([IDL.Text], [Section], ['query']),
    'installSection' : IDL.Func([IDL.Text, IDL.Text], [Merchant], []),
    'removeSection' : IDL.Func([IDL.Text, IDL.Text], [Merchant], []),
    'updateMerchantPlan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Merchant],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };