/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Merchant {
    installedSectionIds: Array<string>;
    billingStatus: string;
    shopDomain: string;
    installDate: bigint;
    planType: string;
}
export interface Section {
    id: string;
    name: string;
    tags: Array<string>;
    description: string;
    category: string;
    isPro: boolean;
}
export interface backendInterface {
    getAllSections(): Promise<Array<Section>>;
    getInstalledSections(shopDomain: string): Promise<Array<Section>>;
    getMerchant(shopDomain: string): Promise<Merchant>;
    getMerchantStats(shopDomain: string): Promise<{
        totalInstalled: bigint;
        billingStatus: string;
        planType: string;
    }>;
    getSection(id: string): Promise<Section>;
    installSection(shopDomain: string, sectionId: string): Promise<Merchant>;
    removeSection(shopDomain: string, sectionId: string): Promise<Merchant>;
    updateMerchantPlan(shopDomain: string, newPlan: string, billingStatus: string): Promise<Merchant>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllSections(): Promise<Array<Section>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSections();
            return result;
        }
    }
    async getInstalledSections(arg0: string): Promise<Array<Section>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstalledSections(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstalledSections(arg0);
            return result;
        }
    }
    async getMerchant(arg0: string): Promise<Merchant> {
        if (this.processError) {
            try {
                const result = await this.actor.getMerchant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMerchant(arg0);
            return result;
        }
    }
    async getMerchantStats(arg0: string): Promise<{
        totalInstalled: bigint;
        billingStatus: string;
        planType: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMerchantStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMerchantStats(arg0);
            return result;
        }
    }
    async getSection(arg0: string): Promise<Section> {
        if (this.processError) {
            try {
                const result = await this.actor.getSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSection(arg0);
            return result;
        }
    }
    async installSection(arg0: string, arg1: string): Promise<Merchant> {
        if (this.processError) {
            try {
                const result = await this.actor.installSection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.installSection(arg0, arg1);
            return result;
        }
    }
    async removeSection(arg0: string, arg1: string): Promise<Merchant> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSection(arg0, arg1);
            return result;
        }
    }
    async updateMerchantPlan(arg0: string, arg1: string, arg2: string): Promise<Merchant> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMerchantPlan(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMerchantPlan(arg0, arg1, arg2);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
